[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*>
    -<l298n_test.cpp>
    -<servo_test.cpp>
    -<encoder_pulse_test.cpp>
    -<encoder_calib_test.cpp>
lib_deps =
    electroniccats/MPU6050 @ ^1.0.0
    me-no-dev/AsyncTCP @ ^1.1.1

[env:l298n_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<l298n_test.cpp>

[env:servo_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<servo_test.cpp>

[env:encoder_pulse_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<encoder_pulse_test.cpp>

[env:encoder_calib_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<encoder_calib_test.cpp>
